server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 7200


tomcat:
  ajp:
    protocol: AJP/1.3
    port: 9002

spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    enabled: true
    restart:
      enabled: true
    cache: false
    check-template-location: true

devtools: #jsp파일 서버 재시작 없이 바로 적용하기
  spring-boot-devtools livereload:
    enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  livereload:
    enabled: true
  thymeleaf:
    cache: false
  restart:
    enabled: true
