server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 7200


tomcat:
  ajp:
    protocol: AJP/1.3
    port: 9002

devtools: #jsp파일 서버 재시작 없이 바로 적용하기
  spring-boot-devtools livereload:
    enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  livereload:
    enabled: true
  thymeleaf:
    cache: false
  restart:
    enabled: true


spring:
  resource:
    static-location: classpath:/static
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    enabled: true
    restart:
      enabled: true
    cache: false
    check-template-location: true
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/order_lee?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wnanswjqtn1@#
    driver: com.mysql.cj.jdbc.Driver
    mapper-locations: classpath:/mapper/**/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml
