server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 7200


tomcat:
  ajp:
    protocol: AJP/1.3
    port: 9002

devtools: #jsp파일 서버 재시작 없이 바로 적용하기
  spring-boot-devtools livereload:
    enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  livereload:
    enabled: true
  thymeleaf:
    cache: false
  restart:
    enabled: true


spring:
  resource:
    static-location: classpath:/static
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    enabled: true
    restart:
      enabled: true
    cache: false
    check-template-location: true
  datasource:
#    driver: com.mysql.cj.jdbc.Driver     #mysql.driver
#    jdbc-url: jdbc:mysql://127.0.0.1:3306/lanterlt?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    #jdbc-url: jdbc:mariadb://localhost:3306/lanterlt?characterEncoding=UTF-8&serverTimezone=UTC
    jdbc-url: ENC(DctImt+AR5wFzaPVWnB44DkIKt30GdFw9qDRSpVsB5JML6CEkauX66CVJN3sH24hhWW6jZh0pQgDt7AE/PHzEMq87ziQU5gUNyfuzdRt3gP1qK/H4iTY+eVK2tk4FOz0VkoCM/9lJ2n8PPGEaMpw5CA7eek2hXcBHfJhN590FkE=)
    username: lanterlt
    password: dkagh3421@@
    mapper-locations: classpath:/mapper/**/*.xml

jasypt:
  encryptor:
    bean: jasyptEncryptor

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml
